# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler. DO NOT EDIT.
# source: pipeline/protos/event_insights.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    6,
    "",
    "pipeline/protos/event_insights.proto",
)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$pipeline/protos/event_insights.proto\x12\x15pipeline.grpc_example"!\n\x10ListUsersRequest\x12\r\n\x05limit\x18\x01 \x01(\x05"%\n\x11ListUsersResponse\x12\x10\n\x08user_ids\x18\x01 \x03(\t"2\n\x10UserStatsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05"(\n\tPageCount\x12\x0c\n\x04page\x18\x01 \x01(\t\x12\r\n\x05count\x18\x02 \x01(\x05">\n\x08PageView\x12\x10\n\x08event_id\x18\x01 \x01(\t\x12\x12\n\nevent_time\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x03 \x01(\t"\xbb\x01\n\x11UserStatsResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bevent_count\x18\x02 \x01(\x05\x125\n\x0bpage_counts\x18\x03 \x03(\x0b2 .pipeline.grpc_example.PageCount\x126\n\rrecent_events\x18\x04 \x03(\x0b2\x1f.pipeline.grpc_example.PageView\x12\x11\n\tlast_page\x18\x05 \x01(\t2\xd2\x01\n\rEventInsights\x12^\n\tListUsers\x12\'.pipeline.grpc_example.ListUsersRequest\x1a(.pipeline.grpc_example.ListUsersResponse\x12a\n\x0cGetUserStats\x12\'.pipeline.grpc_example.UserStatsRequest\x1a(.pipeline.grpc_example.UserStatsResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "pipeline.protos.event_insights_pb2",
    _globals,
)
