# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT.
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from pipeline.protos import (
    event_insights_pb2 as pipeline_dot_protos_dot_event__insights__pb2,
)

GRPC_GENERATED_VERSION = "1.65.5"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in event_insights_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
    )


class EventInsightsStub:
    """Reads event-derived user insights from the pipeline."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
            "/pipeline.grpc_example.EventInsights/ListUsers",
            request_serializer=(
                pipeline_dot_protos_dot_event__insights__pb2.ListUsersRequest.SerializeToString
            ),
            response_deserializer=(
                pipeline_dot_protos_dot_event__insights__pb2.ListUsersResponse.FromString
            ),
        )
        self.GetUserStats = channel.unary_unary(
            "/pipeline.grpc_example.EventInsights/GetUserStats",
            request_serializer=(
                pipeline_dot_protos_dot_event__insights__pb2.UserStatsRequest.SerializeToString
            ),
            response_deserializer=(
                pipeline_dot_protos_dot_event__insights__pb2.UserStatsResponse.FromString
            ),
        )


class EventInsightsServicer:
    """Reads event-derived user insights from the pipeline."""

    def ListUsers(self, request, context):
        """Returns distinct users found in recent pageview events."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserStats(self, request, context):
        """Returns recent event counts grouped by page for one user."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EventInsightsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListUsers": grpc.unary_unary_rpc_method_handler(
            servicer.ListUsers,
            request_deserializer=(
                pipeline_dot_protos_dot_event__insights__pb2.ListUsersRequest.FromString
            ),
            response_serializer=(
                pipeline_dot_protos_dot_event__insights__pb2.ListUsersResponse.SerializeToString
            ),
        ),
        "GetUserStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserStats,
            request_deserializer=(
                pipeline_dot_protos_dot_event__insights__pb2.UserStatsRequest.FromString
            ),
            response_serializer=(
                pipeline_dot_protos_dot_event__insights__pb2.UserStatsResponse.SerializeToString
            ),
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pipeline.grpc_example.EventInsights", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "pipeline.grpc_example.EventInsights", rpc_method_handlers
    )
